// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Presentech.DataAccess.Context;

#nullable disable

namespace Presentech.DataAccess.Migrations
{
    [DbContext(typeof(PresentechDbContext))]
    partial class PresentechDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Presentech.DataAccess.Entities.AdministradorEntity", b =>
                {
                    b.Property<int>("id_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_admin"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("contrasena_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("correo_institucional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("id_admin")
                        .HasName("PK_ADMINISTRADORES");

                    b.HasIndex("correo_institucional")
                        .IsUnique()
                        .HasDatabaseName("UQ_ADMINISTRADORES_CORREO");

                    b.ToTable("administradores", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.AsistenciaEntity", b =>
                {
                    b.Property<int>("id_asistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_asistencia"));

                    b.Property<bool>("asistio")
                        .HasColumnType("boolean");

                    b.Property<bool>("atrasado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("id_estudiante")
                        .HasColumnType("integer");

                    b.Property<int>("id_registro")
                        .HasColumnType("integer");

                    b.Property<string>("justificativo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.HasKey("id_asistencia")
                        .HasName("PK_ASISTENCIAS");

                    b.HasIndex("id_estudiante");

                    b.HasIndex("id_registro")
                        .HasDatabaseName("IDX_ASISTENCIAS_REGISTRO");

                    b.ToTable("asistencias", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ClaseEntity", b =>
                {
                    b.Property<int>("id_clase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_clase"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("id_materia")
                        .HasColumnType("integer");

                    b.Property<int>("id_paralelo")
                        .HasColumnType("integer");

                    b.Property<int>("id_profesor")
                        .HasColumnType("integer");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.HasKey("id_clase")
                        .HasName("PK_CLASES");

                    b.HasIndex("id_materia");

                    b.HasIndex("id_paralelo")
                        .HasDatabaseName("IDX_CLASES_PARALELO");

                    b.HasIndex("id_profesor")
                        .HasDatabaseName("IDX_CLASES_PROFESOR");

                    b.ToTable("clases", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ClaseHorarioEntity", b =>
                {
                    b.Property<int>("id_horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_horario"));

                    b.Property<TimeOnly>("hora_fin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("hora_inicio")
                        .HasColumnType("time");

                    b.Property<int>("id_clase")
                        .HasColumnType("integer");

                    b.Property<int>("id_dia")
                        .HasColumnType("integer");

                    b.HasKey("id_horario")
                        .HasName("PK_CLASES_HORARIO");

                    b.HasIndex("id_clase")
                        .HasDatabaseName("IDX_CLASES_HORARIO_CLASE");

                    b.HasIndex("id_dia");

                    b.ToTable("clases_horario", null, t =>
                        {
                            t.HasCheckConstraint("CHK_HORARIO_HORAS", "hora_fin > hora_inicio");
                        });
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.DiaSemanaEntity", b =>
                {
                    b.Property<int>("id_dia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_dia"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("orden")
                        .HasColumnType("integer");

                    b.HasKey("id_dia")
                        .HasName("PK_DIAS_SEMANA");

                    b.HasIndex("orden")
                        .IsUnique()
                        .HasDatabaseName("UQ_DIAS_SEMANA_ORDEN");

                    b.ToTable("dias_semana", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.EstudianteEntity", b =>
                {
                    b.Property<int>("id_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_estudiante"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id_estudiante")
                        .HasName("PK_ESTUDIANTES");

                    b.ToTable("estudiantes", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.MateriaEntity", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_materia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMateria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMateria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("materias", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.OpinionRecomendacionEntity", b =>
                {
                    b.Property<int>("id_opinion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_opinion"));

                    b.Property<string>("aspecto_mas_util")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("aspectos_por_mejorar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("calificacion_usabilidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("id_profesor")
                        .HasColumnType("integer");

                    b.Property<bool>("utilizaria_siguiente_anio")
                        .HasColumnType("boolean");

                    b.HasKey("id_opinion")
                        .HasName("PK_OPINIONES_RECOMENDACIONES");

                    b.HasIndex("id_profesor")
                        .HasDatabaseName("IDX_OPINIONES_PROFESOR");

                    b.ToTable("opiniones_recomendaciones", null, t =>
                        {
                            t.HasCheckConstraint("CHK_OPINIONES_CALIFICACION_USABILIDAD", "calificacion_usabilidad BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ParaleloEntity", b =>
                {
                    b.Property<int>("id_paralelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_paralelo"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("capacidad_maxima")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("id_paralelo")
                        .HasName("PK_PARALELOS");

                    b.ToTable("paralelos", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ParaleloEstudianteEntity", b =>
                {
                    b.Property<int>("id_paralelo_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_paralelo_estudiante"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("id_estudiante")
                        .HasColumnType("integer");

                    b.Property<int>("id_paralelo")
                        .HasColumnType("integer");

                    b.HasKey("id_paralelo_estudiante")
                        .HasName("PK_PARALELO_ESTUDIANTES");

                    b.HasIndex("id_estudiante");

                    b.HasIndex("id_paralelo", "id_estudiante")
                        .IsUnique()
                        .HasDatabaseName("UQ_PE_PARALELO_ESTUDIANTE");

                    b.ToTable("paralelo_estudiantes", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ProfesorEntity", b =>
                {
                    b.Property<int>("id_profesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_profesor"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("contrasena_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("correo_institucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id_profesor")
                        .HasName("PK_PROFESORES");

                    b.HasIndex("correo_institucional")
                        .IsUnique()
                        .HasDatabaseName("UQ_PROFESORES_CORREO");

                    b.ToTable("profesores", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.RegistroAsistenciaEntity", b =>
                {
                    b.Property<int>("id_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_registro"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<int>("id_horario")
                        .HasColumnType("integer");

                    b.Property<string>("observaciones_sesion")
                        .HasColumnType("text");

                    b.Property<int>("total_ausentes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("total_presentes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("id_registro")
                        .HasName("PK_REGISTROS_ASISTENCIA");

                    b.HasIndex("id_horario", "fecha")
                        .IsUnique()
                        .HasDatabaseName("UQ_REGISTRO_HORARIO_FECHA");

                    b.ToTable("registros_asistencia", (string)null);
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.AsistenciaEntity", b =>
                {
                    b.HasOne("Presentech.DataAccess.Entities.EstudianteEntity", "Estudiante")
                        .WithMany("Asistencias")
                        .HasForeignKey("id_estudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ASISTENCIA_ESTUDIANTE");

                    b.HasOne("Presentech.DataAccess.Entities.RegistroAsistenciaEntity", "RegistroAsistencia")
                        .WithMany("Asistencias")
                        .HasForeignKey("id_registro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ASISTENCIA_REGISTRO");

                    b.Navigation("Estudiante");

                    b.Navigation("RegistroAsistencia");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ClaseEntity", b =>
                {
                    b.HasOne("Presentech.DataAccess.Entities.MateriaEntity", "Materia")
                        .WithMany()
                        .HasForeignKey("id_materia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clases_materias");

                    b.HasOne("Presentech.DataAccess.Entities.ParaleloEntity", "Paralelo")
                        .WithMany("Clases")
                        .HasForeignKey("id_paralelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CLASES_PARALELO");

                    b.HasOne("Presentech.DataAccess.Entities.ProfesorEntity", "Profesor")
                        .WithMany("Clases")
                        .HasForeignKey("id_profesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CLASES_PROFESOR");

                    b.Navigation("Materia");

                    b.Navigation("Paralelo");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ClaseHorarioEntity", b =>
                {
                    b.HasOne("Presentech.DataAccess.Entities.ClaseEntity", "Clase")
                        .WithMany("ClasesHorario")
                        .HasForeignKey("id_clase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HORARIO_CLASE");

                    b.HasOne("Presentech.DataAccess.Entities.DiaSemanaEntity", "DiaSemana")
                        .WithMany("ClasesHorario")
                        .HasForeignKey("id_dia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HORARIO_DIA");

                    b.Navigation("Clase");

                    b.Navigation("DiaSemana");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.OpinionRecomendacionEntity", b =>
                {
                    b.HasOne("Presentech.DataAccess.Entities.ProfesorEntity", "Profesor")
                        .WithMany("OpinionesRecomendaciones")
                        .HasForeignKey("id_profesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OPINIONES_PROFESOR");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ParaleloEstudianteEntity", b =>
                {
                    b.HasOne("Presentech.DataAccess.Entities.EstudianteEntity", "Estudiante")
                        .WithMany("ParaleloEstudiantes")
                        .HasForeignKey("id_estudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PE_ESTUDIANTE");

                    b.HasOne("Presentech.DataAccess.Entities.ParaleloEntity", "Paralelo")
                        .WithMany("ParaleloEstudiantes")
                        .HasForeignKey("id_paralelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PE_PARALELO");

                    b.Navigation("Estudiante");

                    b.Navigation("Paralelo");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.RegistroAsistenciaEntity", b =>
                {
                    b.HasOne("Presentech.DataAccess.Entities.ClaseHorarioEntity", "ClaseHorario")
                        .WithMany("RegistrosAsistencia")
                        .HasForeignKey("id_horario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REGISTRO_HORARIO");

                    b.Navigation("ClaseHorario");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ClaseEntity", b =>
                {
                    b.Navigation("ClasesHorario");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ClaseHorarioEntity", b =>
                {
                    b.Navigation("RegistrosAsistencia");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.DiaSemanaEntity", b =>
                {
                    b.Navigation("ClasesHorario");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.EstudianteEntity", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("ParaleloEstudiantes");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ParaleloEntity", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("ParaleloEstudiantes");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.ProfesorEntity", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("OpinionesRecomendaciones");
                });

            modelBuilder.Entity("Presentech.DataAccess.Entities.RegistroAsistenciaEntity", b =>
                {
                    b.Navigation("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
